### ISSUE TITLE
PDOException on 5a35b31 with PHP7.2

### ISSUE THREAD

**Issue by mbazdell** [hydrian/TTRSS-Auth-LDAP#31]
Hello,

I'm running into this error on a brand new setup. It passes the login screen but then just sits at a blank page.

>Uncaught PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "" in /var/www/ttrss/classes/logger/sql.php:21 Stack trace: #0 /var/www/ttrss/classes/logger/sql.php(21): PDOStatement->execute(Array) #1 /var/www/ttrss/classes/logger.php(28): Logger_SQL->log_error(1024, 'Array\n(\n [ho...', '', '', '') #2 /var/www/ttrss/plugins.local/auth_ldap/init.php(84): Logger->log_error(1024, 'Array\n(\n [ho...', '', '', '') #3 /var/www/ttrss/plugins.local/auth_ldap/init.php(284): Auth_Ldap->_log('Array\n(\n [ho...', 1024) #4 /var/www/ttrss/include/functions.php(706): Auth_Ldap->authenticate('testuser', '12345') #5 /var/www/ttrss/classes/handler/public.php(481): authenticate_user('testuser', '12345') #6 /var/www/ttrss/public.php(50): Handler_Public->login() #7 {main} thrown

**Comment by chrbayer** [comment]
I have the same issue, looks like commit 01d22e255f7a026bb0b0324cde1d8a8756c84a20 in the tt-rss repository leads to this problem:
-		$this->pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_WARNING);
+		$this->pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

But I can't say what the rot cause problem is...

**Comment by hydrian** [comment]
Did either of you try switching to non-sql logging? See if that works.

**Comment by chrbayer** [comment]
I will try to change the log method, but something is really wrong with the logging, this should work even with sql logging...
```
PDOStatement::execute(): SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: &quot;&quot;
1. classes/logger/sql.php(21): execute(Array)
2. classes/logger.php(28): log_error(1024, User: admin authentication successful, , , )
3. plugins.local/auth_ldap/init.php(89): log_error(1024, User: admin authentication successful, , , )
4. plugins.local/auth_ldap/init.php(323): _log(User: admin authentication successful)
5. include/functions.php(706): authenticate(admin, XXX)
6. classes/handler/public.php(481): authenticate_user(admin, XXX)
7. public.php(50): login()
```

**Comment by chrbayer** [comment]
With both other logging methods it works...

**Comment by hydrian** [comment]
I haven't changed the logging messages in years, so something changed upstream. It has to be determined if this is a bug from upstream or a change of logging requirements.

**Comment by hydrian** [comment]
@chrbayer It sounds like a bug. If it was a change of requirements, it would have probably still had an issue. 

I'll see what I can find upstream.

**Comment by hydrian** [comment]
@mbazdell,
  Looks like there is some code rot. I'll look into cleaning it up. As a temporary workaround, if you can change your logging type file or syslog and not hit this error.
